'== ENUMERAÇÕES ==
enum StatusProducao {
  AGUARDANDO
  EM_PRODUCAO
  FINALIZADO
  REPROVADO
}

enum StatusOrdem {
  PENDENTE
  APROVADA
  EM_ANDAMENTO
  CONCLUIDA
  CANCELADA
}

enum TipoOcorrencia {
  FALHA_EQUIPAMENTO
  DESVIO_PROCEDIMENTO
  PROBLEMA_QUALIDADE
}

enum StatusMP {
  DISPONIVEL
  RESERVADO
  BLOQUEADO
  VENCIDO
}

enum StatusQualidade {
  APROVADO
  REPROVADO
  PENDENTE
}

enum TipoMovimentacao {
  ENTRADA
  SAIDA
  AJUSTE
  RESERVA
}

enum TipoLocal {
  ESTANTE
  PALETE
  GELADEIRA
  FREEZER
  AREA_QUARENTENA
  AREA_LIMPA
}

enum StatusCliente {
  ATIVO
  INATIVO
  BLOQUEADO
}

enum StatusCotacao {
  RASCUNHO
  ENVIADA
  APROVADA
  RECUSADA
}

enum StatusPedido {
  PENDENTE
  PROCESSANDO
  FATURADO
  ENTREGUE
  CANCELADO
}

enum ResultadoTeste {
  APROVADO
  REPROVADO
  CONDICIONAL
}